### ISSUE TITLE
Tags Honeywel Evohome returned as string in stead of numbers

### ISSUE THREAD

**Issue by efriethoff** [ralfvd/nl.bevlogenheid.evohome#10]
Hi,
First of all thank you very much for your great app. Really great!
I tried to create a flow to check that the selected temperture does not get too high.

I use in the flow editor the app 'Honeywell Evohome' to trigger to tag 'Thermostat' to verify its value.
The values of 'thermostat' and 'temperture' seem here to be returned as string-values.

When I do almost the same with my device of Evohome called 'woonkamer', the tags are returned as numbers.

Could you please make it so that the app can return the tags as numbers too?

Or if you know a workaround to fix this otherwise, please let me know.

Thank you.

Cheers,
Eric

**Comment by ralfvd** [comment]
This will be solved in the next release 1.0.5

**Comment by ralfvd** [comment]
As V2 is now in stable, I'll close this issue. Please create a new issue if you encounter any issue
