### ISSUE TITLE
Temperature can't be set

### ISSUE THREAD

**Issue by bierre** [ralfvd/nl.bevlogenheid.evohome#11]
Whenever when I try to set a temperature through homey, the only thing that happens is that the current temperature in the selected zone changes to a permanent temperature, but no temperature change is done.

**Comment by ralfvd** [comment]
Can you see in the logs ( Settings / Evohome ) what happens immediately after  you set the new temperature.

Do you set the temperature in a flow or via the device card? What Evohome system do you have?

**Comment by bierre** [comment]
Hi Ralf,

I found out is has a delay, that's why I didn't see the changes. It seems to work now.

Thanx!

**Comment by psy0rz** [comment]
I have a similar issue with my round modulation.

When i try to change the temperature via the webui, it doesnt seem to actually set the temperature. When refreshing the widget it has the old temperature again.

I'm using the latest github version.

Output when changing the temp:

```
Response access token: undefined
Userdata: undefined
(node:21303) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property '0' of undefined
22:42:06 [capabilities] set temperature: 1537948 10
setting device temperature: 1537948
setting device temperature: 10.0
91db1612-73fd-4500-91b2-e63b069b185c
Start Session Code: 429
invalid settings
/WebAPI/api/devices/1537948/thermostat/changeableValues/heatSetpoint
(node:21303) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: "value" required in setHeader("sessionId", value)
```

Any tips as to whats wrong? Im willing to fix it myself.

**Comment by psy0rz** [comment]
Ah ..code 429 probably means i've hit some kind of ratelimit.

**Comment by ralfvd** [comment]
Login will be improved in sdk2 version. Progress tracked in issue #17

**Comment by ralfvd** [comment]
Progress tracked in issue #18

**Comment by ralfvd** [comment]
Closing, tracking update  #18
