### ISSUE TITLE
Can't add thermostat

### ISSUE THREAD

**Issue by gpelleboer** [ralfvd/nl.bevlogenheid.evohome#12]
Hello all.

I am trying to add my thermostat, I entered my username and password, this is went ok i get the message "Account settings saved successfully"

But when i try to add a thermostat I cannot find any of my devices if my total connect comfort account. 

I removed all the spaces an special characters in the zone names but that did not bring anything.
in my log i get the message "[Evohome] Recurring Interval devices: 0"

is there any thing i am doing wrong?
thanks!!

**Comment by ljsvv** [comment]
It seems that Honeywell changed some things on their API.

I personally can't get the Quickactions to work anymore...

**Comment by RetroTrek** [comment]
Is it correct that this is still using the "Old" V1 API ?
There is a new V2 API that perhaps solves the issues?

**Comment by XeroxQ** [comment]
Dear Ralf,

Before, you had the Second Evohome App. Why is that one gone?
I use 2 evohomes, and the App finds all 13 devices/rooms, but i can only access the rooms from the second device. Also, the access keeps going out: when i then try to login, it says that there has been to many attempts at login.

Could you solve these problems?
I can make a good donation if you'll like?

**Comment by ralfvd** [comment]
The second location app is still available but as an “alpha” app to avoid confusion in the App Store. 

If you like to have access send me a personal message and I’ll add you. 

This won’t work in homey v2 btw. A rewrite is needed where I plan to incorporate more locations. 

Donations and guest access to your evohome to check multiple locations are both appreciated.

**Comment by Pheerink** [comment]
I am having the same problem. Today updated Homey to 2.0 and using the beta version of this app. Cannot add thermostats

**Comment by ralfvd** [comment]
Did you re-enter your evohome credentials in the app settings? Unfortunately, the way the settings were stored in previous versions was not compatible with Homey SDK2 .  So you need to re-enter them.

**Comment by Pheerink** [comment]
Yes I did. I also deactivated the app and reinstalled it. Thanks

**Comment by Pheerink** [comment]
Thanks for updating the app. It is working now !

**Comment by ralfvd** [comment]
@XeroxQ  the 'second location app' updated for SDK2 is available and is confirmed working (at least at one 'second location').  Let me know if you'd like access.  And I'll remain available for any donations ;-)

**Comment by XeroxQ** [comment]
Hey Ralf,


Yes i would like access. I tried the donate button on apps.athom, but the link is not correct. I did find your paypal account, but you should fix the link on paypal.

I just send some beer-money; have a nice one 😉

What do you need from me to grand me access tot he second location app?

Met vriendelijke groet,

Arie J. Godschalk

Qluster IT

arie@qluster-it.nl<mailto:arie@qluster-it.nl>
06-25268440

[Qluster IT, Print]

Van: ralfvd <notifications@github.com>
Verzonden: zondag 20 januari 2019 14:23
Aan: ralfvd/nl.bevlogenheid.evohome <nl.bevlogenheid.evohome@noreply.github.com>
CC: Arie J. Godschalk <arie@qluster-it.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ralfvd/nl.bevlogenheid.evohome] Can't add thermostat (#12)


@XeroxQ<https://github.com/XeroxQ> the 'second location app' updated for SDK2 is available and is confirmed working (at least at one 'second location'). Let me know if you'd like access. And I'll remain available for any donations ;-)

**Comment by ralfvd** [comment]
Many thanks for the beer money; I’ve sent you a private email with more details. 

My email sometimes ends up in spam, so check your “Junk” folder if you didn’t receive anything yet. And report me as ‘safe’ ;-)

Thanks



On 24 January 2019 at 15:36:05, XeroxQ (notifications@github.com) wrote:

Hey Ralf,


Yes i would like access. I tried the donate button on apps.athom, but the link is not correct. I did find your paypal account, but you should fix the link on paypal.

I just send some beer-money; have a nice one 😉

What do you need from me to grand me access tot he second location app?

Met vriendelijke groet,

Arie J. Godschalk

Qluster IT

arie@qluster-it.nl<mailto:arie@qluster-it.nl>
06-25268440

[Qluster IT, Print]

Van: ralfvd <notifications@github.com>
Verzonden: zondag 20 januari 2019 14:23
Aan: ralfvd/nl.bevlogenheid.evohome <nl.bevlogenheid.evohome@noreply.github.com>
CC: Arie J. Godschalk <arie@qluster-it.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ralfvd/nl.bevlogenheid.evohome] Can't add thermostat (#12)


@XeroxQ<https://github.com/XeroxQ> the 'second location app' updated for SDK2 is available and is confirmed working (at least at one 'second location'). Let me know if you'd like access. And I'll remain available for any donations ;-)

**Comment by ralfvd** [comment]
As V2 is now in stable, I'll close this issue. Please create a new issue if you encounter any issue
