### ISSUE TITLE
State won't change to schedule

### ISSUE THREAD

**Issue by efriethoff** [ralfvd/nl.bevlogenheid.evohome#13]
Homey v2: 
It Works to change the state to 'Afwezig' , but when I want to cancel this state to follow the Schedule again, nothing changes.

Also the dialog is not showing the options correctie, some seem to be merged.

**Comment by ralfvd** [comment]
V2 needs an updated app to sdk2. This needs some serious rewrite.  I cannot provide a timeline at this moment. But it has my attention. 

Progress will be tracked in other created issues, so for now I’ll close this one.
