### ISSUE TITLE
Support for non-evohome honeywell thermostats (eg Lyric T6)

### ISSUE THREAD

**Issue by LanMart** [ralfvd/nl.bevlogenheid.evohome#14]
Hi,

I asked Athom if homey supports my honeywell lyric T6 thermostat and they pointed me to this app.
However, the T6 does not use honeywell evohome control system and app, but the "Honeywell Home" app. 
So now i'm confused. Is my T6 supported by this app, or not? (And if not, do you plan on adding support, or do you know another app?)

Thanks for your answer,

Martijn

**Comment by ralfvd** [comment]
Athom released a separate app for lyric devices. It uses a different api than the evohome devices. 

It can be found here: https://apps.athom.com/app/com.honeywell.lyric
