### ISSUE TITLE
API now available? / SDK2 update?

### ISSUE THREAD

**Issue by Swiftnesses** [ralfvd/nl.bevlogenheid.evohome#18]
Hi everyone,

It seems the API is now officially available?

https://developer.honeywell.com/api-methods

Further, will this app be updated to SDK2 so the settings work with the new V2 Homey update?

Thanks :)

P.S. Would still love that water sensor support...

**Comment by PatrickSannes** [comment]
A +1 for SDK2 support. Would love that.

**Comment by ralfvd** [comment]
This API doesn't seem to be for Evohome but for other Honeywell devices. The Evohome API is still not officially supported. 

I do need to rewrite the app to SDK2 and radically simplify the app to reduce the amount of calls (right now, there is also a mix of v1 API and v2 API calls which doesn't help). 

I am planning to work on this, but time is limited. But I'll do my best to provide it as soon as possible.

**Comment by ralfvd** [comment]
My work-in-progress copy of SDK2 can be found here: https://github.com/ralfvd/nl.bevlogenheid.evohome/tree/sdk2

I will commit to this branch as much development as possible. So if you want to add code, please do!

**Comment by ralfvd** [comment]
Sdk2 update: i am making good progress, quickactions read and set are working. 
Next up is to get the thermostat temperature readings.

**Comment by Lansuper** [comment]
Thank you for working on this issue. Changing temperature now fails for me too and this in the middle of winter...

**Comment by ralfvd** [comment]
I think I've nailed the most important parts. So I've submitted it to Athom for Beta approval.  So beta testers needed to see if someone hits a bug that mine installation won't cover.    You can wait for the Beta release in the app store, or download the Github code: https://github.com/ralfvd/nl.bevlogenheid.evohome/releases/tag/8627d3f

**Comment by ralfvd** [comment]
Beta is now available in the app store.  You will probably need to re-enter your username and password in the settings . Existing flows and devices should remain available ( after re-entering username + password ). 

Please beta-test and let me know the results, so I can push it to stable as soon as possible, now that Homey 2.0 is out.

**Comment by psy0rz** [comment]
awesome, thanks!

**Comment by ralfvd** [comment]
There is a known issue when you start the app, but there are no thermostat devices configured, or if you delete all thermostats while the app is running.  Version 2.0.1 should fix this, and is pending approval in the app store.

Also, remember to enter your username and password in settings. This couldn't be migrated from version 1.

**Comment by ralfvd** [comment]
Just an update ; version 2.0.3 (beta) is pending approval (for 2-3 days now)in the app store. This should solve all login and pairing issues.  I am waiting for Athom to provide feedback so the app can be published asap. Sorry for the delay, but it is outside my control at this moment.

**Comment by ralfvd** [comment]
As V2 is now in stable, I'll close this issue. Please create a new issue if you encounter any issue
