### ISSUE TITLE
Update V2.0?

### ISSUE THREAD

**Issue by PeetersJan** [ralfvd/nl.bevlogenheid.evohome#19]
As it seems, the individual room thermostats are only available in read-only mode.  Will there be an update of this great app?

![2019-01-06 20 21 23](https://user-images.githubusercontent.com/39444710/50740834-0d575e00-11f5-11e9-9794-f29604121114.jpg)
![2019-01-06 20 20 45](https://user-images.githubusercontent.com/39444710/50740835-0d575e00-11f5-11e9-8c57-c5da796dc452.jpg)
![2019-01-06 20 20 54](https://user-images.githubusercontent.com/39444710/50740836-0d575e00-11f5-11e9-9700-1fd48dbb1eb2.jpg)
![2019-01-06 20 21 08](https://user-images.githubusercontent.com/39444710/50740837-0d575e00-11f5-11e9-9c81-86484f85e4b4.jpg)
![2019-01-06 20 21 14](https://user-images.githubusercontent.com/39444710/50740833-0d575e00-11f5-11e9-9ffe-9870fd9d578d.jpg)

**Comment by PeetersJan** [comment]
*First picture should have been posted last; chronological order messed up*

**Comment by ralfvd** [comment]
Yes, an update is being made. And can be tracked in issue #18 , a rewrite is needed. 

So far I have working “quick actions” , next up is to get and set the individual thermostats. 

Working on it as much as post but can’t give an estimated time yet.

**Comment by PeetersJan** [comment]
Hi,
Had some extra time to test today.
Individual thermostats are working just fine; it just takes time for the visualised setpoint to be updated.
Tested on both RC11 and RC12.
Br,
