### ISSUE TITLE
Temperature change in v2.0.3 results in temporary blue temp of 12 degree

### ISSUE THREAD

**Issue by rhannink** [ralfvd/nl.bevlogenheid.evohome#22]
When I change the temp in v2.0.3 for example to 20 degrees and I return to the screen where the Thermostat device is shown, the device shows in blue 12 degree for about a minute. Then it shows the correct new temperature.
![img_4039 2](https://user-images.githubusercontent.com/1661824/51619544-d9887200-1f30-11e9-8494-7b1eb74384fa.jpg)

**Comment by ralfvd** [comment]
This is solved in 2.1.0 which has just been released as beta. Thanks for notifying!

**Comment by ralfvd** [comment]
As this is now also in stable, I will close this issue.
