### ISSUE TITLE
App not working anymore on 1.1.0 (experimental)

### ISSUE THREAD

**Issue by rhannink** [ralfvd/nl.bevlogenheid.evohome#4]
I updated this morning to Homey firmware 1.1.0 (experimental) and now the Evohome app is not working anymore. I cannot login to TCC anymore. I am sure the UserID/Password are ok. Already tried to uninstall/install the app, did not solve the problem.
Until 1.1.0 I used it without any problems.

**Comment by rhannink** [comment]
Hmm, again installed the app, installed it and now its working again.......
Also the Tag "ingestelde temperatuur" as a valid value now. Not sure what the problem was. Honeywell cloud service was working all the time....

Problem now is that I can set the temperature with the desktop app or the IOS app, I see the set temperature in the log and the temperature is set on the thermostat, but the Homey set temperature is not updated anymore ???

And now I get the incorrect settings again on the settings screen and I cannot login anymore....... Something is wrong.

**Comment by ralfvd** [comment]
Do you still have issues ? Otherwise I will close the ticket.

**Comment by rhannink** [comment]
You can close this issue. EvoHome is working fine again...
