### ISSUE TITLE
Target Temperature Insight

### ISSUE THREAD

**Issue by WesRos** [ralfvd/nl.bevlogenheid.evohome#6]
Homey Firmware: 1.1.9
Honeywell Evohome App V1.0.2

The line in Insight who stands for the target temperature is drawn in the wrong way.
![image](https://cloud.githubusercontent.com/assets/8507396/22967649/9eab5770-f367-11e6-999a-bef52227c007.png)
At 1:00PM the target temperature is set on 10 degrees. At 6:00PM the target temperature is set to 16 degrees. So the line between the two dots has been draw like the black line:
![image](https://cloud.githubusercontent.com/assets/8507396/22968030/26a9ea0a-f369-11e6-85e9-b491e92ad20d.png)
(first draw in the timeline (1), after that connect to the new target temperature (2).)

Thank you to built this App!!!

**Comment by ralfvd** [comment]
Is this still an issue? If I look right now ( with homey firmware 1.5 ) the lines seem to be drawn OK. If it's still an issue, my guess is to be not an Evohome app issue, but the way HOmey represents the logged data. The app cannot influence the way the lines are drawn.

**Comment by WesRos** [comment]
Its working fine!

![image](https://user-images.githubusercontent.com/8507396/33167916-64286074-d03f-11e7-9cc3-12e440fdcbd9.png)
