### ISSUE TITLE
Homey logging random 128 degrees

### ISSUE THREAD

**Issue by Swiftnesses** [ralfvd/nl.bevlogenheid.evohome#9]
Ralf,

Screenshot attached (the log isn't long enough to show anything sadly, I'll keep an eye on it).

Some info is here: http://www.automatedhome.co.uk/vbulletin/showthread.php?5121-Evohome-API-Changes-and-Broken-iOS-App

<img width="1378" alt="screen shot 2017-09-04 at 18 05 57" src="https://user-images.githubusercontent.com/1001877/30034835-fee986de-919b-11e7-8e65-1fc9576498a7.png">

**Comment by ralfvd** [comment]
I'll take a look. Can you also download the Insights logging ? Evohome reports it in xy.nn degrees, so I'd like to know if it is 128.00 that is being reported.

The link to the website helps, might even have the 'test-script' in it to trigger this behaviour.

Thanks!

**Comment by Swiftnesses** [comment]
Attached...
[homey-device-470650df-0f53-4c64-988d-3f9261faba1b.measure_temperature.txt](https://github.com/ralfvd/nl.bevlogenheid.evohome/files/1275258/homey-device-470650df-0f53-4c64-988d-3f9261faba1b.measure_temperature.txt)

**Comment by ralfvd** [comment]
I made some adjustments in the code , and it is running now locally to see if there are any issues, also trying to emulate the '128' , but so far not successful.  Once it is running smoothly for a day or 2, I'll update the app store version.

**Comment by Swiftnesses** [comment]
Perhaps we can help you test it?

**Comment by ralfvd** [comment]
I just published the code on GitHub, so if you can do a local install (keep the settings), then you could do a local test




-------- Original Message --------

**Comment by ralfvd** [comment]
1.0.3 & 1.0.4 is released in the app store, this  fixes the 128 insight logging

**Comment by Swiftnesses** [comment]
Thanks Ralf, appreciate it!

Now, let's get that water thermostat added, my oil bill would love you for the data 👍
